services:
  hlds-classic:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: hlds-classic
    container_name: hlds-classic
    restart: unless-stopped
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "26900:26900/udp"
    volumes:
      - ./server:/home/steam/hlds/
